[project]
name = "datasamorybot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "pytelegrambotapi>=4.27.0",
    "python-telegram-bot>=22.1",
]
